{{- if .Values.vault_settings.gcp_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-database-host/versions/latest" 
        fileName: "db-host"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-iam-db-user/versions/latest" 
        fileName: "iam-db-user"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-iam-db-password/versions/latest" 
        fileName: "iam-db-password"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-iam-db/versions/latest" 
        fileName: "iam-db"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/feature-personal-org/versions/latest" 
        fileName: "feature-personal-org"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/keycloak-certs-endpoint/versions/latest" 
        fileName: "keycloak-certs-endpoint"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/message-broker-driver/versions/latest" 
        fileName: "message-broker-driver"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-message-broker-connection-string/versions/latest" 
        fileName: "message-broker-connection-string"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/auth-enabled/versions/latest" 
        fileName: "auth-enabled"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/access-mode/versions/latest" 
        fileName: "access-mode"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/customization-url/versions/latest" 
        fileName: "customization-url"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-userinfo-endpoint/versions/latest" 
        fileName: "userinfo-endpoint"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/smtp-login/versions/latest" 
        fileName: "smtp-login"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/smtp-from-address/versions/latest" 
        fileName: "smtp-from-address"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/smtp-password/versions/latest" 
        fileName: "smtp-password"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/smtp-host/versions/latest" 
        fileName: "smtp-host"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/smtp-port/versions/latest" 
        fileName: "smtp-port"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/user-guide-link/versions/latest" 
        fileName: "user-guide-link"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_iam.secretName }}
      type: Opaque
      data:
      - objectName: "user-guide-link"
        key: user-guide-link
      - objectName: "smtp-port"
        key: smtp-port
      - objectName: "smtp-host"
        key: smtp-host
      - objectName: "smtp-password"
        key: smtp-password
      - objectName: "smtp-login"
        key: smtp-login
      - objectName: "smtp-from-address"
        key: smtp-from-address
      - objectName: "userinfo-endpoint"
        key: userinfo-endpoint
      - objectName: "customization-url"
        key: customization-url
      - objectName: "keycloak-certs-endpoint"
        key: keycloak-certs-endpoint
      - objectName: "message-broker-connection-string"
        key: message-broker-connection-string
      - objectName: "message-broker-driver"
        key: message-broker-driver
      - objectName: "feature-personal-org"
        key: feature-personal-org
      - objectName: "db-host"
        key: db-host
      - objectName: "iam-db-user"
        key: iam-db-user
      - objectName: "iam-db-password"
        key: iam-db-password
      - objectName: "iam-db"
        key: iam-db
      - objectName: "access-mode"
        key: access-mode
      - objectName: "auth-enabled"
        key: auth-enabled
{{- end }}
