{{- if .Values.vault_settings.aws_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.vault_settings.aws_secret_manager_region }}
    objects: |
      - objectName: "app-secret-key"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "keycloak-certs-endpoint"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "message-broker-driver"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "message-broker-connection-string"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "userinfo-endpoint"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "user-guide-link"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "smtp-host"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "smtp-login"
        objectType: "secretsmanager"
      - objectName: "smtp-from-address"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "smtp-password"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "smtp-port"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "iam-db-user"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "iam-db-password"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "db-host"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "iam-db"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "access-mode"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "auth-enabled"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "feature-personal-org"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "customization-url"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_iam.secretName }}
      type: Opaque
      data:
        - objectName: "customization-url"
          key: customization-url
        - objectName: "user-guide-link"
          key: user-guide-link
        - objectName: "feature-personal-org"
          key: feature-personal-org
        - objectName: "iam-db-user"
          key: iam-db-user
        - objectName: "iam-db-password"
          key: iam-db-password
        - objectName: "db-host"
          key: db-host
        - objectName: "iam-db"
          key: iam-db
        - objectName: "smtp-port"
          key: smtp-port
        - objectName: "smtp-password"
          key: smtp-password
        - objectName: "smtp-login"
          key: smtp-login
        - objectName: "smtp-host"
          key: smtp-from-address
        - objectName: "smtp-from-address"
          key: smtp-host
        - objectName: "userinfo-endpoint"
          key: userinfo-endpoint
        - objectName: "keycloak-certs-endpoint"
          key: keycloak-certs-endpoint
        - objectName: "message-broker-driver"
          key: message-broker-driver
        - objectName: "message-broker-connection-string"
          key: message-broker-connection-string
        - objectName: "app-secret-key"
          key: app-secret-key
        - objectName: "access-mode"
          key: access-mode
        - objectName: "auth-enabled"
          key: auth-enabled
{{- end }}