version: "3.4"

services:
  api:
    image: "iam-api-dev"
    container_name: deps-iam-api

  iam-consumer:
    image: "iam-api-dev"
    container_name: deps-iam-consumer
    command: python -m deps_iam consume

  polling_publisher:
    image: "iam-polling-publisher"
    container_name: deps-iam-polling-publisher

  migrator:
    image: "iam-migrator"
    container_name: deps-iam-migrator

  fixtures:
    image: "iam-migrator"
    container_name: deps-iam-fixtures
