{{- if .Values.vault_settings.aws_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
spec:
  provider: aws
  parameters:
    region: {{ .Values.vault_settings.aws_secret_manager_region }}
    objects: |
      - objectName: "iam-db-user"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "iam-db-password"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "db-host"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "iam-db"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_iam_migrator.secretName }}
      type: Opaque
      data:
        - objectName: "iam-db-user"
          key: iam-db-user
        - objectName: "iam-db-password"
          key: iam-db-password
        - objectName: "db-host"
          key: db-host
        - objectName: "iam-db"
          key: iam-db
{{- end }}