iam:
  image:
    path: "/deps-presale-x01/deps-iam-api"
    pullPolicy: Always
  resources:


iam_consumer:
  image:
    path: "/deps-presale-x01/deps-iam-api"
    pullPolicy: Always

polling_publisher:
  image:
    path: "/deps-presale-x01/deps-iam-polling-publisher"
    pullPolicy: Always

migrator:
  image:
    path: "/deps-presale-x01/deps-iam-migrator"
    pullPolicy: Always

fixtures:
  image:
    path: "/deps-presale-x01/deps-iam-migrator"
    pullPolicy: Always

iam_settings:
  ENV: presale

  DATABASE_REQUIRE_SECURE_TRANSPORT: false

migration_settings:
  DATABASE_REQUIRE_SECURE_TRANSPORT: false

  helm:
  helm_logs_job_enabled: false

csi:
  vault_namespace: 'k8s-presale'
  roleName: 'k8s-presale'
  vaultKubernetesMountPath: 'kubernetes-presale'

service_account:
  serviceAccountName: 'deps-presale'
